runtime: go115
env: standard
# handlers:
# - url: /.*
#   script: main.go
env_variables:
  secretkey: okayletsrockandroll
  DbURL: mongodb+srv://yashi:Doraemon&1@cluster0.2pscc.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  SMTP_KEY: 3c00f30e08727673f60cbab04ca3e4a2
  SMTP_PASS: 3658491e742f5fa9d2f54fa1d76a556f